name: Calling reusable workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/reusable_workflow.yml
