name: Calling reusable workflow

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      bool_value:
        description: 'Boolean value'
        required: true
        type: boolean

jobs:
  build:
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      bool_value: ${{ inputs.bool_value }}
