name: Calling reusable workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/reusable_workflow.yml
