name: Main

on:
  push:
    paths:
      - 'assets/*'
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@0.8.0
        with:
          script: |
            github.a.createComment({
              issue_number: context.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'pong'
            })
