name: Reusable workflow(Just only running checkout)

on:
  workflow_call:
    inputs:
      bool_value:
        description: 'Boolean value'
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: gh pr list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print bool_value
        env:
          BOOL_VALUE: ${{ inputs.bool_value }}
        run: echo "$BOOL_VALUE"
      - name: Proceed if bool_value is true
        if: ${{ inputs.bool_value }}
        run: echo "bool_value is true"
