name: test peter-evans/repository-dispatch

on:
  push:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        id: app-token
        with:
          app-id: 969979
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: sota1235/github_actions_sandbox
          event-type: test_result
          client-payload: '{"passed": false, "message": "This is a failure message"}'
